
<?php echo $this->headLink()->appendStylesheet('/css/index.css')?>
<?php echo $this->headScript()->appendFile('/js/jquery.bxSlider.min.js');?>
<?php echo $this->headScript()->appendFile('/js/jquery_adslider.js');?>


<div class="inner aslider">
	<div class='flash'>
		<ul id='slider' class='list-none'>
			<li><a href='' target='_blank' title=''> <img
					src='/images/1393499756.jpg' alt=''></a></li>
			<li><a href='' target='_blank' title=''> <img
					src='/images/1393500564.jpg' alt=''></a></li>
			<li><a href='' target='_blank' title=''> <img
					src='/images/1393500857.jpg' alt=''></a></li>
			<li><a href='' target='_blank' title=''> <img
					src='/images/1393500564.jpg' alt=''></a></li>
		</ul>
	</div>
	<script type='text/javascript'>$(document).ready(function(){ $('#slider').bxSlider({ mode:'vertical',autoHover:true,auto:true,pager: true,pause: 5000,controls:false});});</script>
</div>
<!-- end of aslider -->

<script type="text/javascript">
<!--

/* $(function(){

	 var txt ="密码重置成功，请记住您的新密码";
		var url="/index/index";
	    shownotice(txt,1000,url);

	
}); */

//-->
</script>