<div class="inner">
	<div class="porcenter">

		<div class="regMenu">
			<span id="regTab"><a>用户注册</a></span> <span id="regTab"><a>用户登入</a></span>
			<span id="regTab" class="active"><a>修改密码</a></span> <span id="regTab"><a>找回密码</a></span>
			<span id="regTab"><a> 重置密码</a></span>

		</div>

		<form class="accountform" id="" action="/account/login" method="post">
			<p>
				<span class="regtlx">原 始 密 码</span> <input placeholder="请输入原始密码"
					style="width: 250px;" type="password" name="password" id="password"
					size="20" value="" class="inp inw" /> <span class="cp_tip"
					id="password_tip"></span>
			</p>
			<p>
				<span class="regtlx">新&nbsp;&nbsp;&nbsp;密&nbsp;&nbsp;&nbsp;码</span>
				<input placeholder="请输入新的密码" style="width: 250px;" type="password"
					size="30" name="newpassword" id="newpassword" class="inp inw" /> <span
					class="cp_tip" id="newpassword_tip"></span>
			</p>
			<p>
				<span class="regtlx">再 次 确 认</span> <input placeholder="请重新输入您新的密码"
					style="width: 250px;" type="password" size="30" name="cnewpassword"
					id="cnewpassword" class="inp inw" /> <span class="cp_tip"
					id="cnewpassword_tip"></span>
			</p>
			<p>
			
			
			<div id="cpnl_alarm"></div>
			</p>
			<span class="regtlx">&nbsp;</span> <input type="button" class="btns"
				value="确   认" id="submitbtn" style="width: 110px; height: 34px;" />
		</form>

	</div>

	<div id="processImage">
		<div class="center-process-image">
			<img src="/images/process.gif">
		</div>
	</div>

</div>

<script>

var istrueofpassword = false;
var istrueofnewpassword = false;
var istrueofcnewpassword = false;

$('#password').focus(function(){
	  $('#password_tip').empty();
	  $(this).css("border", "1px solid #5793F6");
	});
$('#password').focusout(function(){
	
	$('#password_tip').empty();
	var password=$(this).val().trim();
	var img = "<img src='/images/alarm.png'  />";
	var txt ="";
	if(password.length<6){		
		txt = "你输入的密码不正确";
		$(this).css("border", "1px solid red");
		$('#password_tip').append(img,txt);
		return;
	}else{
		   $.ajax({
	            url:"/account/checkpassword",   // url that will use
	            data:{                  // data that will be sent
	            	password:password
	            },          
	            type:"POST",            // type of submision
	            dataType:"text",        // what type of data we'll get back
	            success:function(data)
	            {   
	            	if(data == false ) {
	                	txt = "你输入的密码不正确";
	            		$('#password_tip').append(img,txt);
	            		$('#password').css("border", "1px solid red");
	            		return                 
	                 }
	                 if(data == true) { 
	                	 istrueofpassword = true;
	                	 return;
		                }
	            }
	        });

		}	
});

$('#newpassword').focus(function(){
	  $('#newpassword_tip').empty();
	  var img = "<img src='/images/notice.png'  />";
	  var txt = "密码需由6-16个字母、数字和符号组成，区分大小写";
	  $(this).css("border", "1px solid #5793F6");
	  $('#newpassword_tip').append(img,txt);
	});
$('#newpassword').focusout(function(){
	$('#newpassword_tip').empty();
	var img = "<img src='/images/alarm.png'  />";
	var txt ="";
	var newpassword=$(this).val().trim();
	if(newpassword.length<6 || newpassword.length>16){
		txt = "密码需由6-16个字母、数字和符号组成，区分大小写";
		$('#newpassword_tip').append(img,txt);
		$(this).css("border", "1px solid red");
		return;
	}
	istrueofnewpassword =true;
});

$('#cnewpassword').focus(function(){
	  $('#cnewpassword_tip').empty();
	  var img = "<img src='/images/notice.png'  />";
	  var txt = "请再次输入您的密码";
	  $(this).css("border", "1px solid #5793F6");
	  $('#cnewpassword_tip').append(img,txt);
	});

$('#cnewpassword').focusout(function(){
	$('#cnewpassword_tip').empty();
	var img = "<img src='/images/alarm.png'  />";
	var txt ="";
	var cnewpassword=$(this).val().trim();
	var newpassword=$("#newpassword").val().trim();
	if(cnewpassword != newpassword || cnewpassword==""){
		txt = "您输入的密码不匹配，请重新输入";
		$('#cnewpassword_tip').append(img,txt);
		$(this).css("border", "1px solid red");
		return;
	}
	istrueofcnewpassword = true;
});

//get login user status
var islogin ="<?php if( $_SESSION['user']){echo true;}?>";

$('#submitbtn').click(function(){
	$('#cpnl_alarm').empty();
	$('#password_tip').empty();
    if(!islogin){ 	
    	var img = "<img src='/images/alarm.png'  />";
    	var txt ="您还没登入，请先登入后再修改密码";
    	$('#cpnl_alarm').append(img,txt);   
    	$('#cpnl_alarm').css("color", "red");     
        return;
    }
    var opassword=$('#password').val().trim();
	var img = "<img src='/images/alarm.png'  />";
	var txt ="";
	if(opassword.length<6){		
		txt = "你输入的密码不正确";
		$('#password').css("border", "1px solid red");
		$('#password_tip').append(img,txt);
		return;
	}else{
		   $.ajax({
	            url:"/account/checkpassword",   // url that will use
	            data:{                  // data that will be sent
	            	password:opassword      
	            },          
	            type:"POST",            // type of submision
	            dataType:"text",        // what type of data we'll get back
	            success:function(data)
	            {   
	            	if(data){
	            		istrueofpassword = false
	            		return;
	                 }else{ 
	                	 istrueofpassword = true;
		                }
	            }
	        });

		}	
    var newpassword=$('#newpassword').val().trim();
	
	if( istrueofpassword && istrueofnewpassword && istrueofcnewpassword){
		
			  $.ajax({		   
		            url:"/account/changepassword",
		            data:{              
		                password:newpassword   
		            },          
		            type:"POST",           
		            dataType:"text", 
		            success:function(data)
		            {  	
			             $('#cpnl_alarm').empty();	
		            	 if(data){
		            		    var img = "<img src='/images/notice.png'  />";
		            	    	var txt ="密码已修改成功！";
								var url="/index/index";
		            	    	shownotice(txt,30, url);
		            	        return;
				        	  //window.location.href='/account/processsuccess'; 
				          }
		            	 if(data==null){
				        	    var img = "<img src='/images/alarm.png'  />";
		            	    	var txt ="密码修改失败！";
		            	    	$('#cpnl_alarm').append(img,txt);
		            	    	$('#cpnl_alarm').css("color", "red");
		            	        return;
				          }				          
			        
		            }
		            
		        });
		}	
    
	
}); 
</script>