<div class="inner">
	<div class="porcenter">

		<div class="regMenu">

			<span id="regTab"><a href="javascript:void(0);" onclick="">用户注册</a></span>
			<span id="regTab"><a href="javascript:void(0);" onclick="">用户登入</a></span>
			<span id="regTab" class="active"><a href="javascript:void(0);"
				onclick=""> 找回密码</a></span> <span id="regTab"><a
				href="javascript:void(0);" onclick=""> 重置密码</a></span> <span
				id="loginTab">还没有帐号？<a href="/account/register"> 立即注册 >></a></span>
		</div>

		<form class="accountform" id="" action="/account/login" method="post">
			<div id="login_error"></div>
			<p>
				<span class="regtlx">用 户 名</span> <input placeholder="您的用户名（可选）"
					type="text" value="" class="inp inw" name="username" id="username" />
				<span id="username_tip"></span>
			</p>
			<p>
				<span class="regtlx">邮 箱</span> <input placeholder="请输入您的注册邮箱"
					type="text" name="email" id="email" class="inp inw" /> <span
					id="email_tip"></span>
			</p>
			<p>
				<span class="regtlx">验 证 码</span> <input placeholder="请输入右边的字符"
					type="text" name="checkcode" id="chekcode" class="inp inw" /> <span
					id="form_captcha"></span> <span id="chekcode_tip"></span>

			</p>

			<span class="regtlx">&nbsp;</span> <input type="button" class="btns"
				value="确  认" id="submitbtn" style="width: 110px; height: 34px;" />
		</form>

	</div>


</div>



<script>


// $('#username').focus(function(){
// 	  $('#username_tip').empty();
// 	  $(this).css("border", "1px solid #5793F6");
// 	});

function captcha(){
    //request captcha image
    $.ajax({
         url: "/myzhinan/captcha",
         success: function(data) {
          //handle response from server
          if(data)
            $("#form_captcha").html("<img id='captchaimage' src='/images/captcha/"+data+".png'>");
        }
    });
}

$(document).ready(function() {
    captcha();
});

$("#form_captcha").click(function() {
	captcha();

	});
$('#chekcode').focus(function(){
	$('#chekcode_tip').empty();
	  $(this).css("border", "1px solid #5793F6");
	  var img = "<img src='/images/notice.png'  />";
	  var txt = "看不清？点击换一张";
	  $('#chekcode_tip').append(img,txt);
	  
	});

$('#chekcode').focusout(function(){
	$('#chekcode_tip').empty();
	var chekcode=$('#chekcode').val().trim();
    if(chekcode==''){
    	$('#chekcode').css("border", "1px solid red");
      }
	});


var istrueofusername = true;
var istrueofmail = false;
var istrueofcheckcode = true;
$('#username').focus(function(){
	  $(this).css("border", "1px solid #5793F6");    
	});
$('#email').focus(function(){
	  $(this).css("border", "1px solid #5793F6");  	  
	});

$('#username').focusout(function(){
	$('#username_tip').empty();
	var username=$(this).val().trim();
	var img = "<img src='/images/alarm.png'  />";
	var txt ="";
	if(username!=""){
		$.ajax({			   
	          url:"/account/checkusername",   // url that will use
	          data:{                  // data that will be sent
	              username:username      
	          },          
	          type:"POST",            // type of submision
	          dataType:"text",        // what type of data we'll get back
	          success:function(data)
	          {    
	              if(data>0) {		              	              	
	          		istrueofusername = true; 
	          	   $('#username').css("border", "1px solid #5793F6");           
	               }else{ 
	            	    txt = "此用户名已不存在";                	
		          		$('#username_tip').append(img,txt);
		          		$('#username').css("border", "1px solid red");
	              	     istrueofusername = false;
		                }
	          }
	     });
	}		
});
$('#email').focusout(function(){

	$('#email_tip').empty();
	var email=$(this).val().trim();
	var img = "<img src='/images/alarm.png'  />";
	var txt ="";
	if(email!=""){
		$.ajax({			   
	          url:"/account/checkemail",   // url that will use
	          data:{                  // data that will be sent
	        	  email:email      
	          },          
	          type:"POST",            // type of submision
	          dataType:"text",        // what type of data we'll get back
	          success:function(data)
	          {    
	              if(data>0) {		              	              	
	            	  istrueofmail = true; 
	            	  $('#email').css("border", "1px solid #5793F6");                      
	               }else{ 
	            	    txt = "此邮箱未注册";                	
		          		$('#email_tip').append(img,txt);
		          		$('#email').css("border", "1px solid red");
		          		istrueofmail = false;
		                }
	          }
	     });
	}
	$('#email').css("border", "1px solid red");  		
});

$("#submitbtn").click(function(){
	$('#login_error').empty();
	var username=$('#username').val().trim();
	var email=$('#email').val().trim();
	var chekcode=$('#chekcode').val().trim();	
	if (istrueofusername && istrueofmail && istrueofcheckcode && chekcode!=""){
		showProcessImage();
		  $.ajax({		   
	            url:"/account/getpassword",   
	            data:{   
	            	username: username,             
	            	email:email,
	            	chekcode:chekcode    
	            },          
	            type:"POST",           
	            dataType:"text", 
	            success:function(data)
	            {  		            	           
		          if(data>0){
		        	  clearProcessImage();
			          if(data==3){
			        	 
			        	  var img = "<img src='/images/alarm.png'  />";
			              txt = "验证码输入错误，请重新再试";
			      		  $('#login_error').append(img,txt);
			      			     		  			      		  
			          }else{
			        	 
			        	  var txt ="请登入您的邮箱, 重置密码";
						  var url="/index/index";
		            	  shownotice(txt,15, url);   
		        	    //window.location.href='/account/checkemailnotice';  
			          }
		          }else{
		        	
		           }
	            }
	            
	        });

	 }
});


</script>