<div id="header" class="win1000">
	<a id="logo" href="/index/index"><img alt="新西兰最全面信息指南"
		src="/images/logo2.png" /></a>
	<div id="cityname" class="regname">
		<span>用户登入</span>
	</div>
	<div id="logintext">
		<a href="/index/index/">返回首页</a>|<a target="_blank" href="#">帮助</a>
	</div>
</div>

<div id="login_form">

	<form action="/account/login" method="post">
		<p>
			<label>用 户 名:</label> <input type="text" name="username"
				placeholder="您的用户名或邮箱地址">
		</p>
		<p>
			<label>密&nbsp; &nbsp; &nbsp;&nbsp;码:</label> <input type="password"
				name="password" placeholder="您的密码"><br>
		</p>
		<input type="submit" value="登&nbsp;&nbsp;入">
		<div id="forgetps">
			<a href="javascript:">找回密码</a> <span>| </span><a
				href="/account/register">注册</a>
		</div>

	</form>

</div>