
<div class="cb win1000">

	<div class="porleft">

		<div class="regMenu">

			<span id="regTab"><a>用户注册</a></span> <span id="regTab"><a>用户登入</a></span>
			<span id="regTab"><a>找回密码</a></span> <span id="regTab" class="active"><a>
					重置密码</a></span> <span id="loginTab">已有账号？<a href="/account/login">
					直接登录 >></a></span>
		</div>
            <?php  $email=$this->data['email']; $resetcode=$this->data['resetcode'];?>
			<form id="signupForm" action="/account/create" method="post">

			<div class="regWrap">
				<div id="origReg">
					<div style="margin: 20px 0 0 80px; color: red;" id="login_error"></div>
					<div id="passwordCon">
						<input type="hidden" name="email" value=<?=$email;?>> <input
							type="hidden" name="resetcode" value=<?=$resetcode;?>>
						<p>
							<span class="regtlx">密 码</span> <input type="password" size="30"
								name="password" id="password" class="inp inw" /> <span
								class="register-notice" id="password_tip"></span>
						</p>
						<p id="cpp">
							<span class="regtlx">密&nbsp;码&nbsp;确&nbsp;认</span> <input
								type="password" size="30" name="cpassword" id="cpassword"
								class="inp inw" /> <span id="cpassword_tip"
								class="register-notice"></span>
						</p>
					</div>
					<p>
						<span class="regtlx">验 证 码</span> <input placeholder=""
							type="text" name="checkcode" id="checkcode" class="inp inw"
							style="width: 140px;" /> <span id="form_captcha"></span> <span
							id="checkcode_tip"></span>
					</p>
					<p class="submitwrap">
						<span class="regtlx">&nbsp;</span> <input type="button"
							class="btns" value="确&nbsp;&nbsp;认" id="submitbtn"
							style="width: 110px; height: 34px;" />
					</p>

				</div>
			</div>
		</form>

	</div>

	<div id="processImage">
		<div class="center-process-image">
			<img src="/images/process.gif">
		</div>
	</div>
</div>


<script type="text/javascript">

function captcha(){
    //request captcha image
    $.ajax({
         url: "/myzhinan/captcha",
         success: function(data) {
          //handle response from server
          if(data)
            $("#form_captcha").html("<img id='captchaimage' src='/images/captcha/"+data+".png'>");
        }
    });
}

$(document).ready(function() {
    captcha();
});

$("#form_captcha").click(function() {
	captcha();
	});
$('#checkcode').focus(function(){
	$('#checkcode_tip').empty();
	  $(this).css("border", "1px solid #5793F6");
	  var img = "<img src='/images/notice.png'  />";
	  var txt = "看不清？点击换一张";
	  $('#checkcode_tip').append(img,txt);
	  
	});

$('#checkcode').focusout(function(){
	$('#checkcode_tip').empty();
	var chekcode=$('#checkcode').val().trim();
    if(chekcode==''){
    	$('#checkcode').css("border", "1px solid red");
    	txt = "验证码不能为空";
    	var img = "<img src='/images/alarm.png'  />";
		$('#checkcode_tip').append(img,txt);    	
      }
	});

var istrueofpassword=false;
var istrueofcpassword=false;

$('#password').focus(function(){
	
	  $('#password_tip').empty();
	  var img = "<img src='/images/notice.png'  />";
	  var txt = "密码需由6-16个字母、数字和符号组成，区分大小写";
	  $(this).css("border", "1px solid #5793F6");
	  $('#password_tip').append(img,txt);
	  istrueofpassword=false;
	});	
$('#cpassword').focus(function(){
	  $('#cpassword_tip').empty();
	  var img = "<img src='/images/notice.png'  />";
	  var txt = "请再次输入您的密码";
	  $(this).css("border", "1px solid #5793F6");
	  $('#cpassword_tip').append(img,txt);
	  var istrueofcpassword=false;
	});

$('#password').focusout(function(){
	$('#password_tip').empty();
	var img = "<img src='/images/alarm.png'  />";
	var txt ="";
	var password=$(this).val().trim();
	if(password.length<6 || password.length>16){
		txt = "密码需由6-16个字母、数字和符号组成，区分大小写";
		$('#password_tip').append(img,txt);
		$(this).css("border", "1px solid red");
		istrueofpassword = false;
		return;
	}
	istrueofpassword =true;
});
$('#cpassword').focusout(function(){
	$('#cpassword_tip').empty();
	var img = "<img src='/images/alarm.png'  />";
	var txt ="";
	var cpassword=$(this).val().trim();
	var password=$("#password").val().trim();
	if(password != cpassword || cpassword==""){
		txt = "您输入的密码不匹配，请重新输入";
		$('#cpassword_tip').append(img,txt);
		$(this).css("border", "1px solid red");
		istrueofcpassword = false;
		return;
	}
	istrueofcpassword = true;
});

var resetcode='<?php echo $resetcode;?>';
var email='<?php echo $email;?>';

$('#submitbtn').click(function(){

	$('#login_error').empty();	 
    if(!email){
    	  var img = "<img src='/images/alarm.png'  />";
    	  txt = "你无权重置密码";
    	    $('#login_error').append(img,txt);
    	    $("#processImage").css("display",'none');
    	    return;
      }
   
	var password=$('#password').val().trim();
	var cpassword=$('#cpassword').val().trim();
	var checkcode =$('#checkcode').val().trim();
	var img = "<img src='/images/alarm.png'  />";	
	
    if(password==""){
    	$('#password_tip').empty();
    	txt = "密码不能为空";
		$('#password').css("border", "1px solid red");
		$('#password_tip').append(img,txt);
    }
    if(cpassword==""){
    	$('#cpassword_tip').empty();
    	txt = "密码确认不能为空";
		$('#cpassword').css("border", "1px solid red");
		$('#cpassword_tip').append(img,txt);
    }
    if(checkcode==""){
    	$('#checkcode_tip').empty();
    	txt = "验证码不能为空";
		$('#checkcode').css("border", "1px solid red");
		$('#checkcode_tip').append(img,txt);
    }

	if(resetcode && email && istrueofpassword && istrueofcpassword && checkcode!=""){	
			   showProcessImage();
			   $.ajax({		   
		            url:"/account/resetpassword",   
		            data:{ 
		            	resetcode:resetcode,           
		                email:email, 
		                password:password,
		                checkcode:checkcode    
		            },  		                    
		            type:"POST",           
		            dataType:"text", 
		            success:function(data)
		            {  	
		               clearProcessImage();		            	           
		               if(data==3){
			        	    var img = "<img src='/images/alarm.png'  />";
			        	    txt = "验证码输入错误，请重新再试";
			        	    $('#login_error').append(img,txt);

			           }
				       if(data==2){
				            var img = "<img src='/images/alarm.png'  />";
				        	txt = "您的重置码已过期，请查看最新收到的邮件！";
				        	$('#login_error').append(img,txt);
				       }
				       if(data==1){
					         $("#processImage").empty();				         
					         var txt ="密码重置成功，请记住您的新密码";
							 var url="/index/index";
				             shownotice(txt,5,url); 
		        	        // window.location.href='/account/resetpasswordsuccess'; 
			           } 
				       if(data==0){
					         $("#processImage").empty();				         
					         var txt ="密码重置失败，请记稍后再试";
					         $('#login_error').append(img,txt);

			           }   
				     
		            }
		            
		        });
		}	
});



</script>