<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>新西兰指南网-帐号管理</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf8" />
<script type="text/javascript">document.domain = '58.com';try{var ____json4fe = {catentry:{dispid:'',name:'',listname:''},locallist:{dispid:'',name:'',listname:''},modules:'passport'}}catch(e){}; </script>
<script src="/js/jQuery1.7.2.js" type="text/javascript"></script>
<link rel="stylesheet" href="/css/account.css" type="text/css" />
<?php echo $this->headScript()->appendFile('/js/ajax.js');?>
<link rel="stylesheet" href="/css/style.css" type="text/css">
<?php echo $this->headScript()->appendFile('/js/zhinan.js');?>

<script type="text/javascript">
var cur_tab = 'weixin';
</script>
</head>

<body>

	<div id="header" class="win1000">
		<a id="logo" href="/index/index"><img alt="新西兰最全面信息指南"
			src="/images/logo2.png" /></a>
		<div id="cityname" class="regname">
			<span>帐户管理</span>
		</div>
		<div id="logintext">
			<a href="/index/index/">返回首页</a>|<a target="_blank" href="#">帮助</a>
		</div>
	</div>
 
 <?php echo $this->layout()->content; ?>
 
 
 </body>
</html>


<?php
// $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
// $this->headTitle()->setSeparator(' - ');
// $this->headTitle('新西兰指南网-帐号管理');
// echo $this->doctype();
?>