<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>新西兰指南网</title>
<meta name="keywords" content="" />
<link rel="stylesheet" href="/css/style.css" type="text/css">
<script src="/js/jQuery1.7.2.js" type="text/javascript"></script>
<script src='/js/menu_slider.js' type='text/javascript'></script>
<?php echo $this->headScript()->appendFile('/js/zhinan.js');?>
</head>
<body>


<?php echo $this->layout()->content; ?>


</body>
</html>